import { defineConfig, devices } from '@playwright/test';

/**
 * PlaywrightPro - Main Playwright configuration
 * Generated by PlaywrightPro Chrome Extension
 *
 * CLI usage:
 *   npx playwright test                          # Run all tests
 *   npx playwright test --project=chrome        # Run on Chrome only
 *   npx playwright test tests/TC-001-login.spec.ts  # Run specific test
 *   npx playwright test --headed                # Show browser
 *   npx playwright test --ui                    # Open Playwright UI
 */
export default defineConfig({
  testDir: './generated-tests',
  outputDir: './test-results',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 1,
  workers: process.env.CI ? 1 : 2,
  timeout: 30_000,
  reporter: [
    ['html', { outputFolder: 'playwright-report', open: 'never' }],
    ['json', { outputFile: 'test-results/results.json' }],
    ['junit', { outputFile: 'test-results/results.xml' }],
    ['list'],
  ],
  use: {
    baseURL: process.env.BASE_URL || '',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'on-first-retry',
    channel: 'chrome',
    headless: process.env.CI ? true : false,
    viewport: { width: 1280, height: 720 },
    actionTimeout: 30_000,
    navigationTimeout: 30_000,
  },
  projects: [
    {
      name: 'chrome',
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chrome',
      },
    },
    {
      name: 'chromium-ci',
      use: {
        ...devices['Desktop Chrome'],
        // Uses bundled Chromium — for CI environments where Chrome is not installed
      },
    },
  ],
});
