import { Script, RecordedAction, TestCase } from '../types';
import { buildLocatorCode } from './selectorBuilder';

export function generatePlaywrightScript(script: Script): string {
  const { testCase, actions } = script;
  const lines: string[] = [];

  lines.push(`import { test, expect } from '@playwright/test';`);
  lines.push(`import * as path from 'path';`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Test Case: ${testCase.number}`);
  lines.push(` * Name: ${testCase.name}`);
  lines.push(` * Description: ${testCase.description}`);
  lines.push(` * Expected Result: ${testCase.expectedResult}`);
  lines.push(` * Generated by: PlaywrightPro Chrome Extension`);
  lines.push(` * Generated at: ${new Date().toISOString()}`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`test.describe('${testCase.number}: ${sanitize(testCase.name)}', () => {`);

  const navigateActions = actions.filter((a) => a.type === 'navigate');
  if (navigateActions.length > 0) {
    lines.push(`  test.beforeEach(async ({ page }) => {`);
    lines.push(`    await page.goto('${navigateActions[0].url}');`);
    lines.push(`  });`);
    lines.push(``);
  }

  lines.push(`  test('${sanitize(testCase.name)}', async ({ page }) => {`);

  const nonNavActions = actions.filter(
    (a, i) => !(a.type === 'navigate' && i === actions.findIndex((x) => x.type === 'navigate'))
  );

  if (testCase.steps) {
    lines.push(`    // Steps: ${testCase.steps.replace(/\n/g, ' | ')}`);
  }
  lines.push(``);

  let screenshotIndex = 1;
  for (const action of nonNavActions) {
    const code = generateActionCode(action, screenshotIndex, testCase.number);
    if (action.type === 'screenshot') screenshotIndex++;
    lines.push(...code.map((l) => `    ${l}`));
  }

  lines.push(`  });`);
  lines.push(`});`);
  lines.push(``);

  return lines.join('\n');
}

function generateActionCode(
  action: RecordedAction,
  screenshotIndex: number,
  tcNumber: string
): string[] {
  const lines: string[] = [];
  const locator = buildLocatorCode(action.selector, '', action.value);

  if (action.description) {
    lines.push(`// ${action.description}`);
  }

  switch (action.type) {
    case 'navigate':
      lines.push(`await page.goto('${action.url}');`);
      break;

    case 'click':
      lines.push(`await ${locator}.click();`);
      break;

    case 'fill':
      lines.push(`await ${locator}.fill('${escapeString(action.value || '')}');`);
      break;

    case 'select':
      lines.push(`await ${locator}.selectOption('${escapeString(action.value || '')}');`);
      break;

    case 'check':
      lines.push(`await ${locator}.check();`);
      break;

    case 'uncheck':
      lines.push(`await ${locator}.uncheck();`);
      break;

    case 'hover':
      lines.push(`await ${locator}.hover();`);
      break;

    case 'press':
      lines.push(`await page.keyboard.press('${action.value}');`);
      break;

    case 'wait':
      lines.push(`await page.waitForTimeout(${action.value || 1000});`);
      break;

    case 'screenshot': {
      const filename = `${tcNumber}-step-${screenshotIndex}`;
      lines.push(`await page.screenshot({`);
      lines.push(`  path: path.join('screenshots', '${filename}.png'),`);
      lines.push(`  fullPage: false,`);
      lines.push(`});`);
      if (action.screenshotDescription) {
        lines.push(`// Evidence: ${action.screenshotDescription}`);
      }
      break;
    }

    case 'assertion':
      lines.push(...generateAssertionCode(action, locator));
      break;
  }

  lines.push('');
  return lines;
}

function generateAssertionCode(action: RecordedAction, locator: string): string[] {
  if (action.assertionDescription) {
    const lines = [`// Assert: ${action.assertionDescription}`];
    lines.push(...buildAssertionLine(action, locator));
    return lines;
  }
  return buildAssertionLine(action, locator);
}

function buildAssertionLine(action: RecordedAction, locator: string): string[] {
  switch (action.assertionType) {
    case 'toBeVisible':
      return [`await expect(${locator}).toBeVisible();`];
    case 'toBeHidden':
      return [`await expect(${locator}).toBeHidden();`];
    case 'toHaveText':
      return [`await expect(${locator}).toHaveText('${escapeString(action.assertionValue || '')}');`];
    case 'toContainText':
      return [`await expect(${locator}).toContainText('${escapeString(action.assertionValue || '')}');`];
    case 'toHaveValue':
      return [`await expect(${locator}).toHaveValue('${escapeString(action.assertionValue || '')}');`];
    case 'toHaveURL':
      return [`await expect(page).toHaveURL('${escapeString(action.assertionValue || '')}');`];
    case 'toHaveTitle':
      return [`await expect(page).toHaveTitle('${escapeString(action.assertionValue || '')}');`];
    case 'toBeEnabled':
      return [`await expect(${locator}).toBeEnabled();`];
    case 'toBeDisabled':
      return [`await expect(${locator}).toBeDisabled();`];
    case 'toBeChecked':
      return [`await expect(${locator}).toBeChecked();`];
    case 'toHaveCount':
      return [`await expect(${locator}).toHaveCount(${action.assertionValue || 0});`];
    default:
      return [`await expect(${locator}).toBeVisible();`];
  }
}

function sanitize(str: string): string {
  return str.replace(/'/g, "\\'").replace(/\n/g, ' ');
}

function escapeString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

export function generatePlaywrightConfig(settings: {
  channel: string;
  baseUrl: string;
  timeout: number;
  retries: number;
  workers: number;
  headless: boolean;
}): string {
  return `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  outputDir: './test-results',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : ${settings.retries},
  workers: process.env.CI ? 1 : ${settings.workers},
  timeout: ${settings.timeout},
  reporter: [
    ['html', { outputFolder: 'playwright-report', open: 'never' }],
    ['json', { outputFile: 'test-results/results.json' }],
    ['junit', { outputFile: 'test-results/results.xml' }],
    ['list'],
  ],
  use: {
    baseURL: process.env.BASE_URL || '${settings.baseUrl}',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'on-first-retry',
    channel: '${settings.channel}',
    headless: process.env.CI ? true : ${settings.headless},
  },
  projects: [
    {
      name: 'chrome',
      use: {
        ...devices['Desktop Chrome'],
        channel: '${settings.channel}',
      },
    },
  ],
});
`;
}
